// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcLhbON1Y9St4T6t30lDZuLr2hnNL1q7w',
    appId: '1:69351585548:web:5b6eeb10ebd09ab6a0fb29',
    messagingSenderId: '69351585548',
    projectId: 'fir-authentication-68e7c',
    authDomain: 'fir-authentication-68e7c.firebaseapp.com',
    storageBucket: 'fir-authentication-68e7c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWMWT4uJ9o_Jsto9fqggIqyqf-HOcK1XY',
    appId: '1:69351585548:android:fc3c7bc5859596dca0fb29',
    messagingSenderId: '69351585548',
    projectId: 'fir-authentication-68e7c',
    storageBucket: 'fir-authentication-68e7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy3viX0C4Z-NaMsZOokKKtmDYifIivTtA',
    appId: '1:69351585548:ios:241aff1e6734fc27a0fb29',
    messagingSenderId: '69351585548',
    projectId: 'fir-authentication-68e7c',
    storageBucket: 'fir-authentication-68e7c.firebasestorage.app',
    iosBundleId: 'com.example.a13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy3viX0C4Z-NaMsZOokKKtmDYifIivTtA',
    appId: '1:69351585548:ios:241aff1e6734fc27a0fb29',
    messagingSenderId: '69351585548',
    projectId: 'fir-authentication-68e7c',
    storageBucket: 'fir-authentication-68e7c.firebasestorage.app',
    iosBundleId: 'com.example.a13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcLhbON1Y9St4T6t30lDZuLr2hnNL1q7w',
    appId: '1:69351585548:web:500c0252e2d29f33a0fb29',
    messagingSenderId: '69351585548',
    projectId: 'fir-authentication-68e7c',
    authDomain: 'fir-authentication-68e7c.firebaseapp.com',
    storageBucket: 'fir-authentication-68e7c.firebasestorage.app',
  );
}
