// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(

    apiKey: 'AIzaSyAW1niHJyLfzb3ZsxKyDtjXXudXHd4w5lU',
    appId: '1:95604099882:web:7c3f4fd76f6012b05f2c53',
    messagingSenderId: '95604099882',
    projectId: 'fir-auth-demo-c2bea',
    authDomain: 'fir-auth-demo-c2bea.firebaseapp.com',
    storageBucket: 'fir-auth-demo-c2bea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPfvquIVF9aDhLpX6ceH01Wb6JNtu_8SM',
    appId: '1:95604099882:android:7f58229a805a28815f2c53',
    messagingSenderId: '95604099882',
    projectId: 'fir-auth-demo-c2bea',
    storageBucket: 'fir-auth-demo-c2bea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIWWBhY4QAXN4wmILNqMaFcrbOLygMUvE',
    appId: '1:95604099882:ios:92e5c0f321186db15f2c53',
    messagingSenderId: '95604099882',
    projectId: 'fir-auth-demo-c2bea',
    storageBucket: 'fir-auth-demo-c2bea.firebasestorage.app',

    iosBundleId: 'com.example.a13',
  );

  static const FirebaseOptions macos = FirebaseOptions(

    apiKey: 'AIzaSyCIWWBhY4QAXN4wmILNqMaFcrbOLygMUvE',
    appId: '1:95604099882:ios:92e5c0f321186db15f2c53',
    messagingSenderId: '95604099882',
    projectId: 'fir-auth-demo-c2bea',
    storageBucket: 'fir-auth-demo-c2bea.firebasestorage.app',

    iosBundleId: 'com.example.a13',
  );

  static const FirebaseOptions windows = FirebaseOptions(

    apiKey: 'AIzaSyAW1niHJyLfzb3ZsxKyDtjXXudXHd4w5lU',
    appId: '1:95604099882:web:5be5c455275c84345f2c53',
    messagingSenderId: '95604099882',
    projectId: 'fir-auth-demo-c2bea',
    authDomain: 'fir-auth-demo-c2bea.firebaseapp.com',
    storageBucket: 'fir-auth-demo-c2bea.firebasestorage.app',

  );

}