// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm343YTshU0WZA2R06KTf96NUSLhyuNZM',
    appId: '1:621331339556:web:22410ab22ed3bd7c89bbb1',
    messagingSenderId: '621331339556',
    projectId: 'sign-in-4e919',
    authDomain: 'sign-in-4e919.firebaseapp.com',
    storageBucket: 'sign-in-4e919.firebasestorage.app',
    measurementId: 'G-4HRD0NVKJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdF9LJxrOGG2MupJe3FBtqV4VxhzQvLh4',
    appId: '1:621331339556:android:37a6c0d7178cc9f589bbb1',
    messagingSenderId: '621331339556',
    projectId: 'sign-in-4e919',
    storageBucket: 'sign-in-4e919.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP60Q_F5HHzAOFVcl2gEViGn7ytcZjgTU',
    appId: '1:621331339556:ios:cdc109484acd0bba89bbb1',
    messagingSenderId: '621331339556',
    projectId: 'sign-in-4e919',
    storageBucket: 'sign-in-4e919.firebasestorage.app',
    iosBundleId: 'com.example.a13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP60Q_F5HHzAOFVcl2gEViGn7ytcZjgTU',
    appId: '1:621331339556:ios:cdc109484acd0bba89bbb1',
    messagingSenderId: '621331339556',
    projectId: 'sign-in-4e919',
    storageBucket: 'sign-in-4e919.firebasestorage.app',
    iosBundleId: 'com.example.a13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm343YTshU0WZA2R06KTf96NUSLhyuNZM',
    appId: '1:621331339556:web:c9d04f62aff77b5889bbb1',
    messagingSenderId: '621331339556',
    projectId: 'sign-in-4e919',
    authDomain: 'sign-in-4e919.firebaseapp.com',
    storageBucket: 'sign-in-4e919.firebasestorage.app',
    measurementId: 'G-KWZWCTMFLJ',
  );

}